export function currentFrameTime(): number;
export function currentTime(): number;
export function timeSinceLastFrame(): number;
export function onFrameStart(callback: Function): void;
export function onFrameUpdate(callback: Function): void;
export function onFrameRender(callback: Function): void;
export function onFrameEnd(callback: Function): void;
export function cancelOnFrameStart(callback: Function): void;
export function cancelOnFrameUpdate(callback: Function): void;
export function cancelOnFrameRender(callback: Function): void;
export function cancelOnFrameEnd(callback: Function): void;
